In [1]:
import pandas as pd
import numpy as np

from numpy.linalg import eig

In [2]:
df = pd.read_excel("Dataset/raw_created.xlsx", sheet_name= "Sheet2" , usecols="A,B")

In [3]:
df

x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0
5  2.3  2.7
6  2.0  1.6
7  1.0  1.1
8  1.5  1.6
9  1.1  0.9

In [4]:
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [5]:
sns.scatterplot(df['x'],df['y'])

<AxesSubplot:xlabel='x', ylabel='y'>

In [6]:
df['x'].mean()

1.81

In [7]:
np.mean(df)

x    1.81
y    1.91
dtype: float64

In [8]:
# df['x_xMean'] = df['x']-df['x'].mean()

In [9]:
df

x    y
0  2.5  2.4
1  0.5  0.7
2  2.2  2.9
3  1.9  2.2
4  3.1  3.0
5  2.3  2.7
6  2.0  1.6
7  1.0  1.1
8  1.5  1.6
9  1.1  0.9

In [10]:
mean_by_col = np.mean(df.T, axis = 1)

In [11]:
mean_by_col

x    1.81
y    1.91
dtype: float64

In [12]:
scale_data = df - mean_by_col

In [13]:
scale_data

x     y
0  0.69  0.49
1 -1.31 -1.21
2  0.39  0.99
3  0.09  0.29
4  1.29  1.09
5  0.49  0.79
6  0.19 -0.31
7 -0.81 -0.81
8 -0.31 -0.31
9 -0.71 -1.01

In [14]:
scale_data.T

0     1     2     3     4     5     6     7     8     9
x  0.69 -1.31  0.39  0.09  1.29  0.49  0.19 -0.81 -0.31 -0.71
y  0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01

In [15]:
cov_metrix = np.cov(scale_data.T)

In [16]:
cov_metrix

array([[0.61655556, 0.61544444],
       [0.61544444, 0.71655556]])

In [17]:
Eval , Evec = eig(cov_metrix)

In [18]:
print(Eval)

print(Evec)

[0.0490834  1.28402771]
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [19]:
from sklearn.decomposition import PCA

In [20]:
pca = PCA(n_components=2)
pca.fit_transform(df)

array([[-0.82797019, -0.17511531],
       [ 1.77758033,  0.14285723],
       [-0.99219749,  0.38437499],
       [-0.27421042,  0.13041721],
       [-1.67580142, -0.20949846],
       [-0.9129491 ,  0.17528244],
       [ 0.09910944, -0.3498247 ],
       [ 1.14457216,  0.04641726],
       [ 0.43804614,  0.01776463],
       [ 1.22382056, -0.16267529]])

In [21]:
# Variance explanation ratio by each pc

pca.explained_variance_ratio_

array([0.96318131, 0.03681869])

In [22]:
# sns.scatterplot(pj['x_proj'], pj['y_proj'])